### ISSUE TITLE
Compilation issue of RPC agent.

### ISSUE THREAD

**Issue by kalakatx** [open-amt-cloud-toolkit/rpc#33]
For fixing, added below flag to the CMAKE Command.   
 $sudo cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/cmake ..

**Comment by mpvats-intel** [comment]
Which distro were you using that required explicitly passing in the CMAKE path? For the distros we've tested, the package manager installs cmake to the distro specific path, which ends-up being available via the PATH variable. Thanks!

**Comment by matt-primrose** [comment]
@mpvats-intel provided an answer and no response.  closing issue as resolved.
