### ISSUE TITLE
Add `hostname` parameter to Activation

### ISSUE THREAD

**Issue by lobando** [open-amt-cloud-toolkit/rpc#69]
In some scenarios, for example, when using RPC as a docker container it will pick the hostname of the container (container's ID) you can always override it but as an alternative RPC can take a `hostname` parameter for better tracking

**Comment by matt-primrose** [comment]
Hi @lobando 

With 2.0 release, we have deprecated our C version of RPC.  So we will not be adding new features to this version of RPC.  However, we did add a Go version of RPC (https://github.com/open-amt-cloud-toolkit/rpc-go) and this does have this feature.  Currently RPC-Go is considered "Beta" as we take it through it's paces.
