### ISSUE TITLE
Unable to Run Workflow in actions tab.

### ISSUE THREAD

**Issue by imgonewild** [open-amt-cloud-toolkit/rpc#71]
Unable to run RPC workflow.

I followed the steps: 

1.	Create a fork of rpc on GitHub.
2.	Click on the Actions tab at the top and select Build RPC (Native) Debug/Release.
_3.	Click the Run Workflow dropdown. (I stuck here)_

The page doesnt show the  Run Workflow dropdown button.
So I couldn't build the RPC_Windows.exe file.

If you have any suggestion, please leave a comment, thank you!

![image](https://user-images.githubusercontent.com/45378125/144568198-3f14536d-e362-4d07-a57b-8da13bcaf1d0.png)

**Comment by rsdmike** [comment]
Hey @imgonewild , the screenshot you uploaded shows the wrong one selected. If you select the debug/release( 2nd row on the left) that should give you the option.

**Comment by imgonewild** [comment]
Hey @rsdmike, thanks for the reply. After build in debug/release, I'm not able to download the RPC_Windows.exe file as you provide.(It didnt show up)

Your gif shows:
![image](https://user-images.githubusercontent.com/45378125/144777814-4b9c70dd-aeba-47a8-ac44-63c73cd4976a.png)

In reality, it shows to me:
![image](https://user-images.githubusercontent.com/45378125/144777868-afddf6bb-6919-462a-9456-82b80b820fb4.png)

**Comment by graikhel-intel** [comment]
@imgonewild From the the screenshot you've attached, looks like the build was successful. Just scroll down to artifacts section and you should be able to download rpc binaries. I just forked rpc repository and ran the workflow now

![image](https://user-images.githubusercontent.com/52047020/145135363-20fe8300-f341-4d99-955e-7c720014bac4.png)

Scroll down to the bottom,

![image](https://user-images.githubusercontent.com/52047020/145135420-e5282360-f5a1-448d-b4ad-eb905d680231.png)

**Comment by imgonewild** [comment]
@graikhel-intel thank you, Im able to download the file
