### ISSUE TITLE
MicroLMS

### ISSUE THREAD

**Issue by StumpfMichael** [open-amt-cloud-toolkit/rpc#72]
Hi,
I built MicroLMS as executable (BUILD_LIBRARY OFF) and ran it. I tried to access localhost:16992 with a browser. It was very slow and after entering the credentials of AMT the connection was closed.
A first investigation with strace showed that apparently there is a problem with access to busy resources (futex).
My platform is Centos 7 with devtoolset-9.
Do you have any clues?

**Comment by rsdmike** [comment]
Hey @StumpfMichael -- while those options in the makefile exist -- they are outside of our intended use for this particular project. RPC Is deprecated and we are looking to remove microlms entirely from out toolkit in the future. That said, I would recommend taking a look at: https://www.meshcommander.com/meshcommander/meshcmd which has the option to start lms. It sounds like it could meet your need.

**Comment by StumpfMichael** [comment]
Understood, thank you for your quick answer.
MeshCommander offers working executables of MicroLMS for Windows and Linux. However, Intel tools change quickly and support for Linux is not guaranteed. Therefore we would like to build it from source ourselves and this project is the only place where we could find it.

**Comment by StumpfMichael** [comment]
Bye.
